package eg.projects;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import eg.Projects.ProjectActionsUpdate;
//--Eadgyth--/
import eg.TaskRunner;
import eg.utils.Dialogs;
import eg.utils.SystemParams;

/**
 * Represents a programming project in C#.
 *
 * The class generates a minimalistic .csproj which will replace
 * any existing .csproj generated by other tools.
 */
public final class CSharpProject extends AbstractProject implements ProjectCommands {

   private final TaskRunner runner;

   private static final String INVOKE_DOTNET = "dotnet";

   private String csprojFile     = "";
   private String outputFile     = "";
   private String outputFileName = "";
   private String startCmd       = "";

   public CSharpProject(TaskRunner runner) {
      super(ProjectTypes.CSHARP, "cs", File.separator);
      this.runner = runner;
   }

   @Override
   public void buildSettingsWindow() {
      inputOptions
         .addFileInput(FILE_LABEL, true)
         .addLibrariesInput(LIB_LABEL)
         .addCompileOptionsInput(COMPILE_OPT_LABEL)
         .addBuildNameInput(OUTPUT_NAME_LABEL)
         .addCmdOptionsInput()
         .addCmdArgsInput()
         .buildWindow();
   }

   @Override
   public void enable(ProjectActionsUpdate update) {
      update.enableRun(false);
      update.enableCompile();
   }

   @Override
   public void compile() {
      if (!locateSourceFile()) {
         return;
      }
      if (!generateCsproj()) {
         return;
      }
      runner.runSystemCommand(compileCmd(), "Compile");
   }

   @Override
   public void run() {
      if (!validateFileToRun()) {
         return;
      }
      runner.runSystemCommand(startCmd, "Run " + outputFileName);
   }

   @Override
   public String executableDir() {
      return "bin";
   }

   @Override
   protected void setCommandParameters() {
      outputFile = resolveOutputFile();
      outputFileName = new File(outputFile).getName();
      setStartCmd();
   }

   //
   //--private--/
   //

   /**
    * Generates a minimal .csproj in the project directory
    * based on the current editor settings.
    */
   private boolean generateCsproj() {
      String outputType = resolveOutputType();
      String targetFramework = dotnetTargetFramework();
      if (targetFramework == null) {
         return false;
      }
      StringBuilder xml = new StringBuilder();
      xml.append("<Project Sdk=\"Microsoft.NET.Sdk\">\n");
      xml.append("  <PropertyGroup>\n");
      xml.append("    <OutputType>").append(outputType).append("</OutputType>\n");
      xml.append("    <TargetFramework>").append(targetFramework).append("</TargetFramework>\n");
      xml.append("    <OutputEncoding>utf-8</OutputEncoding>\n");
      if (!buildName(false).isEmpty()) {
         xml.append("    <AssemblyName>").append(buildName(false)).append("</AssemblyName>\n");
      }
      xml.append("  </PropertyGroup>\n");
      if (!libraries().isEmpty()) {
         xml.append("  <ItemGroup>\n");
         for (String lib : libraries()) {
            xml.append("    <Reference Include=\"").append(lib).append("\" />\n");
         }
         xml.append("  </ItemGroup>\n");
      }
      xml.append("</Project>\n");

      String name = buildName(false).isEmpty() ? sourceFileName() : buildName(false);
      name = new File(name).getName();
      csprojFile = projectDir() + File.separator + name + ".csproj";
      try {
         Path path = Paths.get(csprojFile);
         Files.write(path, xml.toString().getBytes(StandardCharsets.UTF_8));
         return true;
      }
      catch (IOException e) {
         Dialogs.errorMessage(
               csprojFile + "\nThe .csproj file could not be written:\n"
               + e.getMessage(),
               "Project file");

         return false;
      }
   }

   private static String dotnetTargetFramework() {
      try {
         Process p = new ProcessBuilder(INVOKE_DOTNET, "--version").start();
         BufferedReader reader = new BufferedReader(
               new InputStreamReader(p.getInputStream()));

         String version = reader.readLine();
         int major = Integer.parseInt(version.split("\\.")[0]);
         return "net" + major + ".0";
      }
      catch (IOException | NumberFormatException | NullPointerException e) {
         Dialogs.errorMessage(
               "The .NET SDK could not be found.\n"
               + "Make sure 'dotnet' is available on the PATH.",
               "dotnet");

         return null;
      }
   }

   private String resolveOutputType() {
      String opts = compileOptions();
      if (opts.contains("t:library")) {
         return "Library";
      }
      else if (opts.contains("t:winexe")) {
         return "WinExe";
      }
      else {
         return "Exe";
      }
   }

   private String resolveOutputFile() {
      String name = buildName(false).isEmpty()
            ? sourceFileName()
            : new File(buildName(false)).getName();

      return projectDir() + File.separator + "bin" + File.separator + name + ".dll";
   }


   private String compileCmd() {
      return INVOKE_DOTNET + " build \"" + csprojFile + "\""
            + " --output \"" + projectDir() + File.separator + "bin\"";
   }

   private boolean validateFileToRun() {
      String msg = "";
      if (compileOptions().contains("t:library")) {
         msg = TARGET_ERR;
      }
      else {
         File f = new File(outputFile);
         if (!f.exists()) {
            msg = DLL_NOT_FOUND_ERR;
         }
      }
      if (!msg.isEmpty()) {
         Dialogs.errorMessage(msg, "Executable output file");
         return false;
      }
      return true;
   }

   private void setStartCmd() {
      StringBuilder sb = new StringBuilder();
      if (SystemParams.IS_WINDOWS) {
         sb.append("cmd.exe /c \"chcp 65001 > nul && ");
      }
      sb.append(INVOKE_DOTNET).append(" ");
      if (!cmdOptions().isEmpty()) {
         sb.append(cmdOptions()).append(" ");
      }
      sb.append("\"").append(outputFile).append("\"");
      if (!cmdArgs().isEmpty()) {
         sb.append(" ").append(cmdArgs());
      }
      if (SystemParams.IS_WINDOWS) {
         sb.append("\"");
      }
      startCmd = sb.toString();
   }

   //
   //-- constants for labels/dialogs --//
   //

   private static final String FILE_LABEL =
         "Name of (main) source file";

   private static final String LIB_LABEL =
         "DLL files";

   private static final String COMPILE_OPT_LABEL =
         "Compiler options (e.g., -t:library or -t:winexe)";

   private static final String OUTPUT_NAME_LABEL =
         "Name for output file (without extension)";

   private static final String TARGET_ERR =
         "The program cannot be run with the currently set target option.";

   private static final String DLL_NOT_FOUND_ERR =
         "\nThe currently set executable file cannot be found."
         + "\nMake sure the project has been compiled successfully.";
}
